In [27]:
print(caldata)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block\n        - HouseAge      median house age in block\n        - AveRooms      average number of rooms\n        - AveBedrms     average number of bedrooms\n        - Population    block population\n        - AveOccup      average house occupancy\n        - Latitude      house block latitude\n        - Longitude     house block longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttp://lib.stat.cmu.edu/datasets/\n\nThe target variable is the median house value for California districts.\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. topic:: References\n\n    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n      Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [5]:
dfX = pd.DataFrame(caldata.data, columns=caldata.feature_names)
dfX

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [9]:
dfy = pd.DataFrame(caldata.target, columns=["Price"])
dfy

       Price
0      4.526
1      3.585
2      3.521
3      3.413
4      3.422
...      ...
20635  0.781
20636  0.771
20637  0.923
20638  0.847
20639  0.894

[20640 rows x 1 columns]

In [11]:
df = pd.concat([dfX, dfy], axis=1)
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [12]:
import statsmodels.api as sm

In [13]:
formula = "Price ~ " + " + ".join(caldata.feature_names)
formula

'Price ~ MedInc + HouseAge + AveRooms + AveBedrms + Population + AveOccup + Latitude + Longitude'

In [14]:
model = sm.OLS.from_formula(formula, data=df)

In [15]:
result = model.fit()

In [17]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.606
Model:                            OLS   Adj. R-squared:                  0.606
Method:                 Least Squares   F-statistic:                     3970.
Date:                Sat, 16 May 2020   Prob (F-statistic):               0.00
Time:                        12:27:55   Log-Likelihood:                -22624.
No. Observations:               20640   AIC:                         4.527e+04
Df Residuals:                   20631   BIC:                         4.534e+04
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -36.9419      0.659    -56.067      0.000     -38.233     -35.650
MedInc         0.4367      0.004    104.054      0.000       0.428       0.445
HouseAge       0.0094      0.000     21.143      0.000       0.009       0.010
AveRooms      -0.1073      0.006    -18.235      0.000      -0.119      -0.096
AveBedrms      0.6451      0.028     22.928      0.000       0.590       0.700
Population -3.976e-06   4.75e-06     -0.837      0.402   -1.33e-05    5.33e-06
AveOccup      -0.0038      0.000     -7.769      0.000      -0.005      -0.003
Latitude      -0.4213      0.007    -58.541      0.000      -0.435      -0.407
Longitude     -0.4345      0.008    -57.682      0.000      -0.449      -0.420
==============================================================================
Omnibus:                     4393.650   Durbin-Watson:                   0.885
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14087.596
Skew:                           1.082   Prob(JB):                         0.00
Kurtosis:                       6.420   Cond. No.                     2.38e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.38e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [23]:
# 스캐일링
formula = "Price ~ " + " + ".join([f"scale({n})" for n in caldata.feature_names])  # f({}) 는 .format과 같은기능과 리스트 컴프리헨션 사용하여 스케일링
formula

'Price ~ scale(MedInc) + scale(HouseAge) + scale(AveRooms) + scale(AveBedrms) + scale(Population) + scale(AveOccup) + scale(Latitude) + scale(Longitude)'

연습문제

In [24]:
data = sm.datasets.get_rdataset("Diamonds", package="Stat2Data")
df = data.data
df.tail()

     Carat Color Clarity  Depth  PricePerCt  TotalPrice
346   0.80     H    VVS2   69.9      3645.0      2916.0
347   0.97     G    VVS1   70.0      5177.3      5021.9
348   1.25     G     VS2   71.9      5607.9      7009.9
349   1.52     F     VS1   70.4      7634.3     11604.1
350   1.72     G     VS1   69.1      8081.1     13899.5

In [25]:
print(data.__doc__)

+----------+-----------------+
| Diamonds | R Documentation |
+----------+-----------------+

Characteristics of a Sample of Diamonds
---------------------------------------

Description
~~~~~~~~~~~

Price and characteristics for a sample of 351 diamonds

Format
~~~~~~

A data frame with 351 observations on the following 6 variables.

+-----------------------------------+-----------------------------------+
| ``Carat``                         | Size of the diamond (in carats)   |
+-----------------------------------+-----------------------------------+
| ``Color``                         | Coded as ``D`` (most              |
|                                   | white/bright) through ``J``       |
+-----------------------------------+-----------------------------------+
| ``Clarity``                       | Coded as ``IF``, ``VVS1``,        |
|                                   | ``VVS2``, ``VS1``, ``VS2``,       |
|                                   | ``SI1``, ``SI2``, or ``SI3``      |
+-----------------------------------+-----------------------------------+
| ``Depth``                         | Depth (as a percentage of         |
|                                   | diameter)                         |
+-----------------------------------+-----------------------------------+
| ``PricePerCt``                    | Price per carat                   |
+-----------------------------------+-----------------------------------+
| ``TotalPrice``                    | Price for the diamond (in         |
|                                   | dollars)                          |
+-----------------------------------+-----------------------------------+
|                                   |                                   |
+-----------------------------------+-----------------------------------+

Details
~~~~~~~

Data for a sample of diamonds. The clarity of the diamonds ranges from
IF (internally flawless) through VVS1 (very,very slightly included), VS1
(very slightly included), to SI3 (slightly included) in the order listed
above.

Source
~~~~~~

Diamond data obtained from AwesomeGems.com on July 28, 2005.

In [30]:
model = sm.OLS.from_formula("TotalPrice ~ Carat", data=df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             TotalPrice   R-squared:                       0.863
Model:                            OLS   Adj. R-squared:                  0.863
Method:                 Least Squares   F-statistic:                     2204.
Date:                Sat, 16 May 2020   Prob (F-statistic):          7.20e-153
Time:                        12:54:36   Log-Likelihood:                -3293.1
No. Observations:                 351   AIC:                             6590.
Df Residuals:                     349   BIC:                             6598.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -7181.2981    347.537    -20.663      0.000   -7864.828   -6497.769
Carat       1.464e+04    311.815     46.946      0.000     1.4e+04    1.53e+04
==============================================================================
Omnibus:                      159.724   Durbin-Watson:                   1.237
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1205.436
Skew:                           1.734   Prob(JB):                    1.75e-262
Kurtosis:                      11.390   Cond. No.                         4.31
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
model = sm.OLS.from_formula("TotalPrice ~ Carat + I(Carat**2)", data=df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             TotalPrice   R-squared:                       0.926
Model:                            OLS   Adj. R-squared:                  0.925
Method:                 Least Squares   F-statistic:                     2168.
Date:                Sat, 16 May 2020   Prob (F-statistic):          3.43e-197
Time:                        12:56:35   Log-Likelihood:                -3186.0
No. Observations:                 351   AIC:                             6378.
Df Residuals:                     348   BIC:                             6390.
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept      -522.7021    466.292     -1.121      0.263   -1439.807     394.403
Carat          2385.9862    752.545      3.171      0.002     905.878    3866.094
I(Carat ** 2)  4498.2062    263.039     17.101      0.000    3980.860    5015.553
==============================================================================
Omnibus:                      125.710   Durbin-Watson:                   1.864
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1166.009
Skew:                           1.214   Prob(JB):                    6.37e-254
Kurtosis:                      11.592   Cond. No.                         18.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [37]:
model = sm.OLS.from_formula("TotalPrice ~ Carat + I(Carat**2) + Depth + C(Color) + 0", data=df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             TotalPrice   R-squared:                       0.940
Model:                            OLS   Adj. R-squared:                  0.939
Method:                 Least Squares   F-statistic:                     595.7
Date:                Sat, 16 May 2020   Prob (F-statistic):          1.28e-202
Time:                        13:00:59   Log-Likelihood:                -3148.0
No. Observations:                 351   AIC:                             6316.
Df Residuals:                     341   BIC:                             6355.
Df Model:                           9
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
C(Color)[D]    7298.8418   1367.466      5.337      0.000    4609.110    9988.573
C(Color)[E]    6962.8167   1372.642      5.073      0.000    4262.905    9662.729
C(Color)[F]    7550.5039   1386.740      5.445      0.000    4822.862    1.03e+04
C(Color)[G]    6925.7723   1397.264      4.957      0.000    4177.431    9674.113
C(Color)[H]    5591.5172   1429.135      3.913      0.000    2780.487    8402.547
C(Color)[I]    3974.5666   1424.379      2.790      0.006    1172.892    6776.242
C(Color)[J]    4931.2735   1721.706      2.864      0.004    1544.773    8317.774
Carat          3896.8539    720.120      5.411      0.000    2480.417    5313.290
I(Carat ** 2)  4172.6227    243.831     17.113      0.000    3693.020    4652.225
Depth          -132.7053     21.527     -6.165      0.000    -175.048     -90.362
==============================================================================
Omnibus:                       89.268   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1250.277
Skew:                           0.605   Prob(JB):                    3.21e-272
Kurtosis:                      12.167   Cond. No.                     2.27e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.27e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [39]:
model = sm.OLS.from_formula("TotalPrice ~ Carat + I(Carat**2) + Depth + C(Color) + C(Clarity)", data=df) # 0 빼면 D color가 베이스 라인이 됨
result = model.fit() 
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             TotalPrice   R-squared:                       0.963
Model:                            OLS   Adj. R-squared:                  0.961
Method:                 Least Squares   F-statistic:                     540.6
Date:                Sat, 16 May 2020   Prob (F-statistic):          1.14e-227
Time:                        13:02:54   Log-Likelihood:                -3064.6
No. Observations:                 351   AIC:                             6163.
Df Residuals:                     334   BIC:                             6229.
Df Model:                          16
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept           1.009e+04   1167.587      8.638      0.000    7788.686    1.24e+04
C(Color)[T.E]         56.1305    280.016      0.200      0.841    -494.686     606.947
C(Color)[T.F]        141.1203    278.881      0.506      0.613    -407.465     689.705
C(Color)[T.G]       -861.6219    284.209     -3.032      0.003   -1420.688    -302.556
C(Color)[T.H]      -2150.8195    369.862     -5.815      0.000   -2878.372   -1423.267
C(Color)[T.I]      -3698.7077    505.150     -7.322      0.000   -4692.385   -2705.031
C(Color)[T.J]      -1632.4418    919.463     -1.775      0.077   -3441.111     176.227
C(Clarity)[T.SI1]  -3074.6096    475.020     -6.473      0.000   -4009.018   -2140.201
C(Clarity)[T.SI2]  -5427.2405    625.742     -8.673      0.000   -6658.133   -4196.348
C(Clarity)[T.SI3]  -6846.8673   1169.744     -5.853      0.000   -9147.861   -4545.874
C(Clarity)[T.VS1]   -976.5625    425.411     -2.296      0.022   -1813.385    -139.740
C(Clarity)[T.VS2]  -1692.6303    431.115     -3.926      0.000   -2540.673    -844.587
C(Clarity)[T.VVS1]   619.5188    482.109      1.285      0.200    -328.834    1567.871
C(Clarity)[T.VVS2]  -823.9503    470.761     -1.750      0.081   -1749.980     102.080
Carat               6232.4639    620.649     10.042      0.000    5011.589    7453.338
I(Carat ** 2)       3555.0137    206.643     17.204      0.000    3148.529    3961.499
Depth               -177.3032     17.545    -10.106      0.000    -211.816    -142.790
==============================================================================
Omnibus:                      134.300   Durbin-Watson:                   1.914
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1368.675
Skew:                           1.291   Prob(JB):                    6.25e-298
Kurtosis:                      12.323   Cond. No.                     1.10e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
fig = sm.graphics.plot_tegress_